FROM node:12-alpine AS BUILD_IMAGE

WORKDIR /app

COPY . /app

RUN npm install
RUN npm run tsc

ENV NODE_ENV=production
RUN npm run migrate-db

FROM node:12-alpine AS DEPENDENCY_IMAGE

WORKDIR /app

COPY . /app

RUN npm install --production=true

FROM node:12-alpine

WORKDIR /app

COPY --from=BUILD_IMAGE /app/dist ./dist
COPY --from=DEPENDENCY_IMAGE /app/node_modules ./node_modules
COPY --from=DEPENDENCY_IMAGE /app/config ./config
COPY --from=DEPENDENCY_IMAGE /app/public ./public
COPY --from=DEPENDENCY_IMAGE /app/package.json .
COPY --from=DEPENDENCY_IMAGE /app/ormconfig.js .

EXPOSE 3500

ENTRYPOINT npm run prod-start
