version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run tsc

  deploy_master_app:
    docker:
      - image: node:11-alpine
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
             apk add --no-cache \
                 python3 \
                 py3-pip \
             && pip3 install --upgrade pip \
             && pip3 install \
                awscli \
             && rm -rf /var/cache/apk/*

      - run:
          name: Configuring AWS
          command: |
            aws configure set aws_access_key_id AKIAZVWKQASVBHOUKSNA
            aws configure set aws_secret_access_key 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
            aws configure set region us-east-1
            aws --version

      - run:
          name: Install Docker
          command: |
            apk add curl
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Sending Docker images to ECR
          command: |
            docker build -t url:latest -f Dockerfile-start .
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 665070863530.dkr.ecr.us-east-1.amazonaws.com
            docker tag url:latest 665070863530.dkr.ecr.us-east-1.amazonaws.com/url_shortner:latest
            docker push 665070863530.dkr.ecr.us-east-1.amazonaws.com/url_shortner:latest


workflows:
  version: 2
  ci:
    jobs:
      # - build

      - deploy_master_app:
          # requires:
          #   - build
          filters:
            branches:
              only: master
