version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  version: 2
  ci:
    jobs:
      - build

      - deploy_master_app:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run tsc

  deploy_master_app:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile-start
          region: AWS_REGION
          repo: url_shortner
