version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run tsc

  deploy_master_app:
    docker:
      - image: node:11-alpine
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
             apk add --no-cache \
                 python3 \
                 py3-pip \
             && pip3 install --upgrade pip \
             && pip3 install \
                awscli \
             && rm -rf /var/cache/apk/*

      - run:
          name: Configuring AWS
          command: |
            aws configure set aws_access_key_id AKIAZVWKQASVBHOUKSNA
            aws configure set aws_secret_access_key 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
            aws configure set region us-east-1
            aws --version

      - run: apk add docker
      - run: apk update
      - run: rc-update add docker boot
      - run: service docker start
      - run: service docker status  
         
      - run: apk add sudo
      - run: service docker start
      # - run: sudo chmod 757 /var/run/docker.sock
      # - run: sudo docker run --privileged=true -v /var/run/docker.sock:/var/run/docker.sock -it ...
      - run: sudo docker build -t url:latest -f Dockerfile-start .
      - run: aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 665070863530.dkr.ecr.us-east-1.amazonaws.com
      - run: sudo docker tag url:latest 665070863530.dkr.ecr.us-east-1.amazonaws.com/url_shortner:latest
      - run: sudo docker push 665070863530.dkr.ecr.us-east-1.amazonaws.com/url_shortner:latest       

workflows:
  version: 2
  ci:
    jobs:
      # - build

      - deploy_master_app:
          # requires:
          #   - build
          filters:
            branches:
              only: master
