version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  version: 2
  ci:
    jobs:
      - build

      - deploy_master_app:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run tsc

  deploy_master_app:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - aws-ecr/deploy:
          account-url: 665070863530.dkr.ecr.us-east-1.amazonaws.com
          aws-access-key-id: AKIAZVWKQASVBHOUKSNA
          aws-secret-access-key: 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
          dockerfile: Dockerfile-start
          region: us-east-1
          repo: url_shortner
             


